owner: SantyTec
repo: upptime

sites:
  - name: SantyTec Store
    url: https://www.santytec.com.ar

status-website:
  baseUrl: /upptime-store
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  introTitle: "**SantyTec Store**"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
